name: klima
description: "KLIMA - The People's DRRM App for Filipino Communities"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  dio: ^5.4.0
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.4.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  
  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  permission_handler: ^11.4.0
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  
  # Camera & Media
  image_picker: ^1.0.5
  camera: ^0.10.6
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  logger: ^2.6.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
